import './_slider';
import './_animation';
import './_listNumbers';
import './_pathAnimation';
import './_conceptAnimation';
import './_initRellax';
import './_sticky';
import './_modal';
import './_mobMenu';
